export const GET_CLUSTER_DATA_REQUEST = "GET_CLUSTER_DATA_REQUEST";
export const GET_CLUSTER_DATA_SUCCESS = "GET_CLUSTER_DATA_SUCCESS";
export const GET_CLUSTER_DATA_FAILURE = "GET_CLUSTER_DATA_FAILURE";
export const CHANGE_CLUSTER_VIEW_KEY = "CHANGE_CLUSTER_VIEW_KEY";
export const SET_CLUSTER_STATUS = "SET_CLUSTER_STATUS";
export const ADD_WORKER_CLUSTER = "ADD_WORKER_CLUSTER";
